name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
  contents: write

jobs:
  build:
    name: Build for Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'

    - name: Build the project
      run: npm run build

    # - name: Run semantic-release
    #   id: semantic-release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   #*Runs semantic release, echos the output, then sets SKIP_UPLOAD if it detects the no relevant changes string
    #   run: |
    #     output=$(npx semantic-release)
    #     echo "$output"
    #     if echo "$output" | grep -q "There are no relevant changes, so no new version is released."; then
    #       echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
    #     fi

    # - name: Capture version
    #   run: echo "VER=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    #   id: set_version
    #   continue-on-error: true

    - name: Deploy
      #*Only execute this step we didn't decide to skip upload
      if:  env.SKIP_UPLOAD != 'true'
      run: npm run deploy
      # uses: JamesIves/github-pages-deploy-action@releases/v4
      # with:
      #   branch: gh-pages
      #   folder: dist
      #   token:  ${{ secrets.GITHUB_TOKEN }}